name: Feature Request
description: Have a feature you'd like to see added? Use this template to request it.
labels: ["enhancement"]
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to let us know your thoughts!
    - type: textarea
      id: detailed
      attributes:
          label: Tell us what you think!
          description: Let us know the details of the feature you'd like to see added, and why you think it'd be a good addition.
          placeholder: I think it'd be cool if...
          value: "I think it'd be cool if..."
      validations:
          required: true
