name: Release messages to discord announcement channel

on: 
  release:
    types:
      - created

jobs:
  run_main:
    runs-on: ubuntu-18.04
    name: Sends custom message
    steps:
      - name: Discord - Styled Releases/Patch Notes
        uses: nhevia/discord-styled-releases@v1.2.3
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID_HOMESITE }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN_HOMESITE }}
